/* ==========================================================================
   PROJECT: RoboData-ETL-PipeLine
   DESCRIPTION: Database and Table Setup for Live Arduino Data Logging
   AUTHOR: Edward Tatem
   DATE: 2026-03-05
   ==========================================================================
*/

-- 1. DATABASE INITIALIZATION
-- This checks if the 'RobotKinematics' database exists before creating it
IF NOT EXISTS (SELECT * FROM sys.databases WHERE name = 'RobotKinematics')
BEGIN
    CREATE DATABASE RobotKinematics;
    PRINT 'Database Created Successfully';
END
GO

-- Switch to the RobotKinematics database context
USE RobotKinematics;
GO

-- 2. SCHEMA DEFINITION
-- This creates the table to store our ETL data if it is not already present
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[EnvironmentServoLog]') AND type in (N'U'))
BEGIN
    CREATE TABLE EnvironmentServoLog (
        LogID INT PRIMARY KEY IDENTITY(1,1), -- Unique ID that increments automatically
        Distance_cm FLOAT,                  -- Decimal distance from Ultrasonic sensor
        Humidity_pct FLOAT,                 -- Humidity percentage from DHT11
        ServoDegree INT,                    -- The current angle of the servo motor
        ButtonPressed VARCHAR(50),          -- The state of the physical hardware button
        ReadingTime DATETIME                -- The timestamp generated by Python for the ETL record
    );
    PRINT 'Table EnvironmentServoLog Created Successfully';
END
GO

-- 3. VERIFICATION
-- Retrieve the 5 most recent entries to confirm the Python pipeline is active
SELECT TOP 5 * FROM EnvironmentServoLog 
ORDER BY ReadingTime DESC;